
language: node_js
node_js:
  - "0.11"
before_script: cd public
script: npm install && bower install && ./node_modules/karma/bin/karma start ../karma.test.config.js
deploy:
  provider: heroku
  api_key: "82acde78-dec8-4f33-809e-45bc05e4db85"
